### ISSUE TITLE
re-run google earth engine code

### ISSUE THREAD

**Issue by coreytcallaghan** [coreytcallaghan/avian-diversity-in-urban-greenspaces#5]
@mitchest 

I pushed the 'final polygons' to the repo. Over the next couple days, can you re-run the google earth code?

If possible, try to fix output. If not, its not the end of the world.

**Comment by coreytcallaghan** [comment]
Forgot to mention this. The shapefile is located in: "Data/Final_study_sites/Shapefile

Cheers!

**Comment by mitchest** [comment]
Are you not wanting the buffers this time? If so, you'll need to redo/check the 5/10/15km buffers yer?

**Comment by mitchest** [comment]
OK, new exports for the hotspots are in the shared google drive - i'll let you sort out how you want that in the repo. The columns are friendlier now, although the geo column is a big string. Just use an import function to pull the .csv and strip the columns needed.

**Comment by coreytcallaghan** [comment]
Hey. I did the buffers, to run the google earth engine code on. They are in the buffers folder - one shapefile for each of 5/15/25 km buffers.

After much debate, I decided not to clip at the coast. I think there are arguments for and against it.

Thanks!

**Comment by mitchest** [comment]
Oops, forgot to move the files over today - all the buffer exports are in the Google share drive now
